services:
  claude-code:
    build: .
    container_name: claude-code-sandbox
    stdin_open: true
    tty: true
    volumes:
      # Mount only the current directory to /workspace (read-write)
      - .:/workspace
      # Mount Claude Code config directory to persist browser login authentication
      - claude-config:/home/claude/.config/claude-code
    working_dir: /workspace
    # Prevent access to host network and other containers
    network_mode: bridge

volumes:
  claude-config:
    driver: local
